spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/todo?serverTimezone=UTC&useSSL=false
    username: root
    password: root.123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  data:
    rest:
      base-path: /api
#debug: true

server:
   port: ${SERVER_PORT:9090}