spring:
  datasource:
    url: jdbc:mysql://services.gcloud.srcb.com:30306/bms?serverTimezone=UTC&useSSL=false
    username: root
    password: root.123
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
   port: 9091


