spring:
  datasource:
    url: jdbc:mysql://119.28.191.18:3306/mytest?serverTimezone=UTC&useSSL=false
    username: root
    password: root.123
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: "classpath:/static"


server:
   port: 8009


