spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://services.gcloud.srcb.com:30306/springboot?serverTimezone=UTC&useSSL=false
    username: root
    password: root.123
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: INFO
