server:
  port: 3035

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: t1
          uri: lb://provider
          predicates:
            - Path=/t1/hello/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=extendtag, 1111111
            - haha
            - IPForbid=127.0.0.1
            - Test=aa,bb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3033/eureka/