


kerberos:
  url: http://10.69.65.242:8011/kerberos/downloadKeytab?tenantid={0}&kdcServerName={1}
  location: D:\test
  krb5: "D:\\save\\krb5.conf"
  hdfsUrl: hdfs://10.69.66.107:8020
  kdcServerName: "test"
  tenant: "1"
  hadoopDir: D:\save\hadoop2.6_Win_x64-master
  props:
    - k: hadoop.security.authentication
      v: kerberos
    - k: hadoop.security.authorization
      v: true
